plugins { id 'com.android.application' }

android {
    namespace 'com.independentstudio.deadzone'
    compileSdk 35
    defaultConfig {
        applicationId 'com.independentstudio.deadzone'
        minSdk 26
        targetSdk 35
        versionCode 6
        versionName '0.9-Cinematic-Intro'
    }
}
